# Generated by Django 6.0.1 on 2026-01-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('county', models.CharField(choices=[('busia', 'Busia'), ('kisumu', 'Kisumu'), ('garissa', 'Garissa'), ('turkana', 'Turkana'), ('marsabit', 'Marsabit'), ('makueni', 'Makueni'), ('nairobi', 'Nairobi'), ('kilifi', 'Kilifi')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Alert',
                'verbose_name_plural': 'User Alerts',
            },
        ),
    ]
