# Generated by Django 6.0.1 on 2026-01-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('risk_type', models.CharField(max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('message', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='useralert',
            options={},
        ),
        migrations.RemoveField(
            model_name='useralert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='useralert',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='useralert',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='county',
            field=models.CharField(max_length=50),
        ),
    ]
