# Generated by Django 6.0.1 on 2026-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_climatealert_suggested_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralert',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=2),
        ),
    ]
